-- Adminer 4.8.0 PostgreSQL 9.6.22 dump

DROP TABLE IF EXISTS "customers";
CREATE TABLE "public"."customers" (
    "customerid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstname" character varying(50) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "lastname" character varying(50) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "gender" character varying(45) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "address" character varying(200) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "phone" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "email" character varying(100) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "city" character varying(20) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "country" character varying(50) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    CONSTRAINT "customers_pkey" PRIMARY KEY ("customerid")
) WITH (oids = false);

INSERT INTO "customers" ("customerid", "firstname", "lastname", "gender", "address", "phone", "email", "city", "country") VALUES
(3,	'Leon',	'Glen',	'Male',	'81 Everton Rd,Gillits',	820832830,	'Leon@gmail.com',	'Durban',	'South Africa'),
(4,	'Charl',	'Muller',	'Male',	'290A Dorset Ecke',	44856872553,	'Charl.muller@yahoo.com',	'Berlin',	'Germany'),
(5,	'Julia',	'Stein',	'Female',	'2 Wernerring',	448672445058,	'Js234@yahoo.com',	'Frankfurt',	'Germany'),
(1,	'Lerato',	'Mabitso',	'Male',	'284 chaucer st',	84789657,	'john@gmail.com',	'Johannesburg',	'South Africa');

DROP TABLE IF EXISTS "employees";
CREATE TABLE "public"."employees" (
    "employeeid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "firstname" character varying(50) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "lastname" character varying(50) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "email" character varying(100) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "jobtitle" character varying(20) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    CONSTRAINT "employees_pkey" PRIMARY KEY ("employeeid")
) WITH (oids = false);

INSERT INTO "employees" ("employeeid", "firstname", "lastname", "email", "jobtitle") VALUES
(1,	'Kani',	'Matthew',	'mat@gmail.com',	'Manager'),
(2,	'Lesly',	'Cronje',	'LesC@gmail.com',	'Clerk'),
(3,	'Gideon',	'Maduku',	'm@gmail.com',	'Accountant');

DROP TABLE IF EXISTS "orders";
CREATE TABLE "public"."orders" (
    "orderid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "productid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "paymentid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "fulfilledbyemployeeid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "daterequired" timestamp DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "dateshipped" timestamp DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "status" character varying(20) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    CONSTRAINT "orders_pkey" PRIMARY KEY ("orderid")
) WITH (oids = false);

INSERT INTO "orders" ("orderid", "productid", "paymentid", "fulfilledbyemployeeid", "daterequired", "dateshipped", "status") VALUES
(1,	1,	1,	2,	'2018-09-05 00:00:00',	NULL,	'Not shipped'),
(2,	1,	2,	2,	'2018-09-04 00:00:00',	'2018-09-03 00:00:00',	'Shipped'),
(3,	3,	3,	3,	'2018-09-06 00:00:00',	NULL,	'Not shipped');

DROP TABLE IF EXISTS "payments";
CREATE TABLE "public"."payments" (
    "customerid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "paymentid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "paymentdate" timestamp DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    "amount" numeric(10,2) DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "payments_pkey" PRIMARY KEY ("paymentid")
) WITH (oids = false);

INSERT INTO "payments" ("customerid", "paymentid", "paymentdate", "amount") VALUES
(1,	1,	'2018-09-01 00:00:00',	150.75),
(4,	3,	'2018-09-03 00:00:00',	700.60),
(5,	2,	'2018-09-03 00:00:00',	150.70);

DROP TABLE IF EXISTS "products";
CREATE TABLE "public"."products" (
    "productid" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "productname" character varying(100) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "description" character varying(300) DEFAULT 'GENERATED BY DEFAULT AS IDENTITY',
    "buyprice" numeric(10,2) DEFAULT GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "products_pkey" PRIMARY KEY ("productid")
) WITH (oids = false);

INSERT INTO "products" ("productid", "productname", "description", "buyprice") VALUES
(1,	'Harley Davidson Chopper',	'This replica features working kickstand, front suspension, gear-shift lever',	150.75),
(2,	'Classic Car',	'Turnable front wheels, steering function',	550.75),
(3,	'Sports car',	'Turnable front wheels, steering function',	700.60);

ALTER TABLE ONLY "public"."orders" ADD CONSTRAINT "orders_fulfilledbyemployeeid_fkey" FOREIGN KEY (fulfilledbyemployeeid) REFERENCES employees(employeeid) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."orders" ADD CONSTRAINT "orders_paymentid_fkey" FOREIGN KEY (paymentid) REFERENCES payments(paymentid) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."orders" ADD CONSTRAINT "orders_productid_fkey" FOREIGN KEY (productid) REFERENCES products(productid) NOT DEFERRABLE;

-- 2021-05-19 06:38:44.405557+00